services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run dev
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev